[package]
name = "rustodo"
version = "0.1.0"
edition = "2021"
author = "Francisco Lala"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
web-sys = "0.3.56"
wasm-bindgen = "0.2"
wasm-logger = "0.2.0"